#!/usr/bin/env python3
"""Build the China NEA 2024 HVDC-system inventory used by the grid atlas.

The source is Table 4-1 of the National Energy Administration's 2024 Annual
Report on National Power Reliability.  The table is transcribed here as
structured facts because the report is a fixed-layout PDF rather than a
machine-readable dataset.  Converter-station names are added only where an
official report table, or the first-party project supplier for the new
Yangzhou-Zhenjiang link, publishes them.  The builder never invents
coordinates or route geometry.

Outputs:

* ``data/grid-atlas/china-nea-hvdc-systems.json``
* ``data/grid-atlas/china-nea-hvdc.metadata.json``

Use ``--source-pdf`` to verify a local copy of the pinned source report and
``--check`` to compare the generated bytes with the committed outputs.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = (
    PROJECT_ROOT / "data" / "grid-atlas" / "china-nea-hvdc-systems.json"
)
DEFAULT_METADATA_OUTPUT = (
    PROJECT_ROOT / "data" / "grid-atlas" / "china-nea-hvdc.metadata.json"
)

DATASET_ID = "cn-nea-reliability-2024-hvdc-systems"
SCHEMA_VERSION = "1.0.0"
BUILD_VERIFIED_ON = "2026-07-26"

SOURCE = {
    "id": "cn-nea-reliability-2024",
    "source_class": "official",
    "evidence_level": "reported",
    "publisher": (
        "国家能源局电力可靠性管理和工程质量监督中心 "
        "(National Energy Administration of China)"
    ),
    "report_title_zh": "2024年全国电力可靠性年度报告",
    "reporting_period": "2024",
    "published_on": "2025-03-31",
    "landing_url": "https://prpq.nea.gov.cn/zxdt/12012.html",
    "alternate_landing_url": "https://prpq.nea.gov.cn/kkxgl/12011.html",
    "pdf_url": (
        "https://prpq.nea.gov.cn/uploads/file1/20250331/"
        "67ea4fb889529.pdf"
    ),
    "pdf_sha256": (
        "af0c088a6c25511ec9fa9f758af374c5a22d0002e2c507a9450f2d64c85e5e95"
    ),
    "primary_table": "4-1",
    "primary_table_title_zh": "2024年纳入可靠性管理的直流输电系统基本情况",
    "primary_table_physical_pdf_pages": [117, 118, 119, 120],
    "primary_table_printed_report_pages": [111, 112, 113, 114],
    "licence": "Official publication terms; factual transcription",
}

NREC_SOURCE = {
    "id": "cn-nrec-yangzhen-hvdc-2024",
    "source_class": "first_party_project_company",
    "evidence_level": "reported",
    "publisher": "南京南瑞继保电气有限公司 (NR Electric)",
    "title_zh": "南瑞继保助力国内首个“交改直”直流输电工程—扬镇直流竣工投运",
    "published_on": "2024-04-29",
    "url": "https://www.nrec.com/cn/index.php/news/info/1634/5",
}

SYSTEM_TYPES = {
    "point_to_point_ehvdc": "点对点超高压直流输电系统",
    "point_to_point_uhvdc": "点对点特高压直流输电系统",
    "back_to_back": "背靠背直流输电系统",
    "multi_terminal": "多端直流输电系统",
}

EXPECTED_SUMMARY = {
    "point_to_point_ehvdc": {
        "system_count": 18,
        "rated_transfer_capacity_mw": 45_464,
        "line_length_km": 15_279,
    },
    "point_to_point_uhvdc": {
        "system_count": 19,
        "rated_transfer_capacity_mw": 150_600,
        "line_length_km": 33_795,
    },
    "back_to_back": {
        "system_count": 9,
        "rated_transfer_capacity_mw": 20_860,
        "line_length_km": 0,
    },
    "multi_terminal": {
        "system_count": 5,
        "rated_transfer_capacity_mw": 16_650,
        "line_length_km": 3_875,
    },
}
EXPECTED_TOTAL = {
    "system_count": 51,
    "rated_transfer_capacity_mw": 233_574,
    "line_length_km": 52_949,
}


def unit(
    label_zh: str,
    commissioned_on: str | None = None,
    voltage_kv: int | None = None,
    capacity_mw: int | None = None,
    source_note_zh: str | None = None,
) -> dict[str, Any]:
    value: dict[str, Any] = {"label_zh": label_zh}
    if commissioned_on:
        value["commissioned_on"] = commissioned_on
    if voltage_kv is not None:
        value["rated_voltage"] = {
            "notation": f"±{voltage_kv}",
            "magnitude_kv": voltage_kv,
        }
    if capacity_mw is not None:
        value["rated_transfer_capacity_mw"] = capacity_mw
    if source_note_zh:
        value["source_note_zh"] = source_note_zh
    return value


def event(commissioned_on: str, scope_zh: str) -> dict[str, str]:
    return {"commissioned_on": commissioned_on, "scope_zh": scope_zh}


def system(
    sequence: int,
    name_zh: str,
    system_type: str,
    capacity_mw: int,
    length_km: int,
    grid_groups: list[str],
    *,
    voltage_kv: int | None = None,
    units: list[dict[str, Any]] | None = None,
    commissioning_events: list[dict[str, str]] | None = None,
    capacity_basis: str = "reported_system_total",
) -> dict[str, Any]:
    value: dict[str, Any] = {
        "nea_sequence": sequence,
        "system_name_zh": name_zh,
        "system_type": system_type,
        "system_type_zh": SYSTEM_TYPES[system_type],
        "rated_transfer_capacity_mw": capacity_mw,
        "capacity_basis": capacity_basis,
        "line_length_km": length_km,
        "grid_groups": grid_groups,
        "units": units or [],
    }
    if voltage_kv is not None:
        value["rated_voltage"] = {
            "notation": f"±{voltage_kv}",
            "magnitude_kv": voltage_kv,
        }
    if commissioning_events:
        value["commissioning_events"] = commissioning_events
    return value


def table_4_1_page(sequence: int) -> tuple[int, int]:
    if sequence <= 9:
        return 117, 111
    if sequence <= 25:
        return 118, 112
    if sequence <= 40:
        return 119, 113
    return 120, 114


def table_source_ref(sequence: int) -> dict[str, Any]:
    physical_page, printed_page = table_4_1_page(sequence)
    return {
        "source_id": SOURCE["id"],
        "table": "4-1",
        "physical_pdf_page": physical_page,
        "printed_report_page": printed_page,
    }


def source_terminal_pair(
    first_name_zh: str,
    second_name_zh: str,
    *,
    source_ref: dict[str, Any],
) -> list[dict[str, Any]]:
    return [
        {
            "terminal_index": 1,
            "station_name_zh": first_name_zh,
            "station_type_zh": "换流站",
            "source_ref": source_ref,
        },
        {
            "terminal_index": 2,
            "station_name_zh": second_name_zh,
            "station_type_zh": "换流站",
            "source_ref": source_ref,
        },
    ]


# Tables 4-5 and 4-8 list converter stations in the same system order as
# Table 4-1.  Names are paired here without adding direction or coordinates.
TERMINAL_PAIRS: dict[int, tuple[str, str]] = {
    1: ("葛洲坝", "南桥"),
    2: ("天生桥", "广州"),
    3: ("龙泉", "政平"),
    4: ("江陵", "鹅城"),
    5: ("宜都", "华新"),
    6: ("兴仁", "宝安"),
    7: ("德阳", "宝鸡"),
    8: ("伊敏", "穆家"),
    9: ("银川东", "胶东"),
    10: ("团林", "枫泾"),
    11: ("柴达木", "拉萨"),
    12: ("从西", "牛寨"),
    13: ("从西", "牛寨"),
    14: ("金官", "桂中"),
    15: ("永仁", "富宁"),
    16: ("浦园", "鹭岛"),
    17: ("绿谷", "黄沙洋"),
    18: ("少游", "圌山"),
    19: ("楚雄", "穗东"),
    20: ("复龙", "奉贤"),
    21: ("锦屏", "苏州"),
    22: ("天山", "中州"),
    23: ("宜宾", "金华"),
    24: ("普洱", "侨乡"),
    25: ("灵州", "绍兴"),
    26: ("祁连", "韶山"),
    27: ("雁门关", "淮安"),
    28: ("扎鲁特", "广固"),
    29: ("锡盟", "泰州"),
    30: ("新松", "东方"),
    31: ("伊克昭", "沂南"),
    32: ("昌吉", "古泉"),
    33: ("青南", "豫南"),
    34: ("雅砻江", "鄱阳湖"),
    35: ("陕北", "武汉"),
    36: ("建昌", "姑苏"),
    37: ("金沙江", "钱塘江"),
}


def build_systems() -> list[dict[str, Any]]:
    ehv = "point_to_point_ehvdc"
    uhv = "point_to_point_uhvdc"
    btb = "back_to_back"
    multi = "multi_terminal"
    state = ["国家电网"]
    southern = ["南方电网"]

    systems = [
        system(1, "葛南直流输电系统", ehv, 1164, 1106, state, voltage_kv=500,
               units=[unit("极Ⅰ", "1989-09-01"), unit("极Ⅱ", "1990-08-01")]),
        system(2, "天广直流输电系统", ehv, 1800, 963, southern, voltage_kv=500,
               units=[unit("极Ⅰ", "2000-12-26"), unit("极Ⅱ", "2001-06-26")]),
        system(3, "龙政直流输电系统", ehv, 3000, 860, state, voltage_kv=500,
               units=[unit("极Ⅰ", "2003-06-01"), unit("极Ⅱ", "2003-06-01")]),
        system(4, "江城直流输电系统", ehv, 3000, 941, state, voltage_kv=500,
               units=[unit("极Ⅰ", "2004-06-01"), unit("极Ⅱ", "2004-06-01")]),
        system(5, "宜华直流输电系统", ehv, 3000, 1060, state, voltage_kv=500,
               units=[unit("极Ⅰ", "2006-12-01"), unit("极Ⅱ", "2006-12-01")]),
        system(6, "兴安直流输电系统", ehv, 3000, 1194, southern, voltage_kv=500,
               units=[unit("极Ⅰ", "2007-12-03"), unit("极Ⅱ", "2007-06-21")]),
        system(7, "德宝直流输电系统", ehv, 3000, 534, state, voltage_kv=500,
               units=[unit("极Ⅰ", "2010-04-21"), unit("极Ⅱ", "2010-04-21")]),
        system(8, "伊穆直流输电系统", ehv, 3000, 913, state, voltage_kv=500,
               units=[unit("极Ⅰ", "2010-09-30"), unit("极Ⅱ", "2010-09-30")]),
        system(9, "银东直流输电系统", ehv, 4000, 1335, state, voltage_kv=660,
               units=[unit("极Ⅰ", "2011-03-25"), unit("极Ⅱ", "2011-03-25")]),
        system(10, "林枫直流输电系统", ehv, 3000, 978, state, voltage_kv=500,
               units=[unit("极Ⅰ", "2011-05-02"), unit("极Ⅱ", "2011-05-02")]),
        system(11, "柴拉直流输电系统", ehv, 600, 1034, state, voltage_kv=400,
               units=[unit("极Ⅰ", "2012-06-10"), unit("极Ⅱ", "2012-06-10")]),
        system(
            12,
            "牛从甲直流输电系统（溪洛渡-广东）",
            ehv,
            3200,
            1225,
            southern,
            voltage_kv=500,
            units=[unit("极Ⅰ", "2014-04-11"), unit("极Ⅱ", "2013-10-12")],
        ),
        system(
            13,
            "牛从乙直流输电系统（溪洛渡-广东）",
            ehv,
            3200,
            1225,
            southern,
            voltage_kv=500,
            units=[unit("极Ⅰ", "2014-06-29"), unit("极Ⅱ", "2014-06-29")],
        ),
        system(14, "金中直流输电系统", ehv, 3200, 1105, southern, voltage_kv=500,
               units=[unit("极Ⅰ", "2016-06-18"), unit("极Ⅱ", "2016-06-18")]),
        system(15, "永富直流输电系统", ehv, 3000, 577, southern, voltage_kv=500,
               units=[unit("极Ⅰ", "2016-06-30"), unit("极Ⅱ", "2016-06-30")]),
        system(16, "厦门柔性直流输电系统", ehv, 2000, 11, state, voltage_kv=320,
               units=[unit("极Ⅰ", "2015-12-17"), unit("极Ⅱ", "2015-12-17")]),
        system(17, "如东柔性直流输电系统", ehv, 1100, 108, ["中国三峡"],
               voltage_kv=400,
               units=[unit("极Ⅰ", "2021-10-19"), unit("极Ⅱ", "2021-10-19")]),
        system(18, "游圌直流输电系统", ehv, 1200, 110, state, voltage_kv=200,
               units=[unit("对称单极", "2024-04-28")]),
        system(19, "楚穗直流输电系统", uhv, 5000, 1374, southern, voltage_kv=800,
               units=[unit("极Ⅰ", "2010-06-18"), unit("极Ⅱ", "2009-12-28")]),
        system(20, "复奉直流输电系统", uhv, 6400, 1907, state, voltage_kv=800,
               units=[unit("极Ⅰ", "2010-07-26"), unit("极Ⅱ", "2010-07-26")]),
        system(21, "锦苏直流输电系统", uhv, 7200, 2078, state, voltage_kv=800,
               units=[unit("极Ⅰ", "2012-12-06"), unit("极Ⅱ", "2012-12-06")]),
        system(22, "天中直流输电系统", uhv, 8000, 2192, state, voltage_kv=800,
               units=[unit("极Ⅰ", "2014-01-25"), unit("极Ⅱ", "2014-01-25")]),
        system(23, "宾金直流输电系统", uhv, 8000, 1653, state, voltage_kv=800,
               units=[unit("极Ⅰ", "2014-07-03"), unit("极Ⅱ", "2014-07-03")]),
        system(24, "普侨直流输电系统", uhv, 5000, 1412, southern, voltage_kv=800,
               units=[unit("极Ⅰ", "2015-05-30"), unit("极Ⅱ", "2014-01-29")]),
        system(25, "灵绍直流输电系统", uhv, 8000, 1720, state, voltage_kv=800,
               units=[unit("极Ⅰ", "2016-08-24"), unit("极Ⅱ", "2016-08-24")]),
        system(26, "祁韶直流输电系统", uhv, 8000, 2383, state, voltage_kv=800,
               units=[unit("极Ⅰ", "2017-06-23"), unit("极Ⅱ", "2017-06-23")]),
        system(27, "雁淮直流输电系统", uhv, 8000, 1119, state, voltage_kv=800,
               units=[unit("极Ⅰ", "2017-06-30"), unit("极Ⅱ", "2017-06-30")]),
        system(28, "鲁固直流输电系统", uhv, 10000, 1234, state, voltage_kv=800,
               units=[unit("极Ⅰ", "2018-01-01"), unit("极Ⅱ", "2018-01-01")]),
        system(29, "锡泰直流输电系统", uhv, 10000, 1620, state, voltage_kv=800,
               units=[unit("极Ⅰ", "2018-01-01"), unit("极Ⅱ", "2018-01-01")]),
        system(30, "新东直流输电系统", uhv, 5000, 1958, southern, voltage_kv=800,
               units=[unit("极Ⅰ", "2018-05-28"), unit("极Ⅱ", "2018-05-28")]),
        system(31, "昭沂直流输电系统", uhv, 10000, 1238, state, voltage_kv=800,
               units=[unit("极Ⅰ", "2019-01-01"), unit("极Ⅱ", "2019-01-01")]),
        system(32, "吉泉直流输电系统", uhv, 12000, 3284, state, voltage_kv=1100,
               units=[unit("极Ⅰ", "2019-07-01"), unit("极Ⅱ", "2019-07-01")]),
        system(33, "青豫直流输电系统", uhv, 8000, 1563, state, voltage_kv=800,
               units=[unit("极Ⅰ", "2019-12-30"), unit("极Ⅱ", "2019-12-30")]),
        system(34, "雅湖直流输电系统", uhv, 8000, 1696, state, voltage_kv=800,
               units=[unit("极Ⅰ", "2021-06-21"), unit("极Ⅱ", "2021-06-21")]),
        system(35, "陕武直流输电系统", uhv, 8000, 1137, state, voltage_kv=800,
               units=[unit("极Ⅰ", "2021-12-21"), unit("极Ⅱ", "2022-09-30")]),
        system(36, "建苏直流输电系统", uhv, 8000, 2087, state, voltage_kv=800,
               units=[unit("极Ⅰ", "2022-12-01"), unit("极Ⅱ", "2022-12-01")]),
        system(37, "金塘直流输电系统", uhv, 8000, 2140, state, voltage_kv=800,
               units=[unit("极Ⅰ", "2023-06-01"), unit("极Ⅱ", "2023-06-01")]),
        system(
            38,
            "灵宝背靠背",
            btb,
            1110,
            0,
            state,
            units=[
                unit("单元Ⅰ", "2005-07-01", 120, 360),
                unit("单元Ⅱ", "2009-12-15", 167, 750),
            ],
            capacity_basis="sum_of_reported_unit_ratings",
        ),
        system(
            39,
            "高岭背靠背",
            btb,
            3000,
            0,
            state,
            units=[
                unit("单元Ⅰ", "2008-11-01", 125, 750),
                unit("单元Ⅱ", "2008-11-01", 125, 750),
                unit("单元Ⅲ", "2012-11-13", 125, 750),
                unit("单元Ⅳ", "2012-11-13", 125, 750),
            ],
            capacity_basis="sum_of_reported_unit_ratings",
        ),
        system(
            40,
            "黑河背靠背",
            btb,
            750,
            0,
            state,
            units=[unit("单元Ⅰ", "2012-01-07", 125, 750)],
            capacity_basis="sum_of_reported_unit_ratings",
        ),
        system(
            41,
            "鲁西背靠背",
            btb,
            3000,
            0,
            southern,
            units=[
                unit("单元Ⅰ", "2016-06-30", 160, 1000),
                unit("单元Ⅱ", "2016-08-29", 350, 1000),
                unit("单元Ⅲ", "2017-06-30", 160, 1000),
            ],
            capacity_basis="sum_of_reported_unit_ratings",
        ),
        system(
            42,
            "宜昌柔性直流背靠背（渝鄂直流北通道）",
            btb,
            2500,
            0,
            state,
            units=[
                unit("单元Ⅰ", "2019-06-01", 420, 1250),
                unit("单元Ⅱ", "2019-06-01", 420, 1250),
            ],
            capacity_basis="sum_of_reported_unit_ratings",
        ),
        system(
            43,
            "施州柔性直流背靠背环流站（渝鄂直流南通道）",
            btb,
            2500,
            0,
            state,
            units=[
                unit("单元Ⅰ", "2019-06-01", 420, 1250),
                unit("单元Ⅱ", "2019-06-01", 420, 1250),
            ],
            capacity_basis="sum_of_reported_unit_ratings",
        ),
        system(
            44,
            "云霄背靠背",
            btb,
            2000,
            0,
            ["国家电网", "南方电网"],
            units=[
                unit("单元Ⅰ", "2022-10-01", 100, 1000),
                unit("单元Ⅱ", "2022-10-01", 100, 1000),
            ],
            capacity_basis="sum_of_reported_unit_ratings",
        ),
        system(
            45,
            "南粤背靠背",
            btb,
            3000,
            0,
            southern,
            voltage_kv=300,
            units=[unit("单元Ⅰ", "2022-05-25"), unit("单元Ⅱ", "2022-05-25")],
        ),
        system(
            46,
            "粤中背靠背",
            btb,
            3000,
            0,
            southern,
            voltage_kv=300,
            units=[unit("单元Ⅰ", "2022-03-29"), unit("单元Ⅱ", "2022-03-29")],
        ),
        system(
            47,
            "禄高肇直流输电系统",
            multi,
            3000,
            1277,
            southern,
            voltage_kv=500,
            units=[unit("极Ⅰ"), unit("极Ⅱ")],
            commissioning_events=[
                event("2004-09-24", "高肇极Ⅰ"),
                event("2004-05-31", "高肇极Ⅱ"),
                event("2020-06-11", "禄高"),
            ],
        ),
        system(
            48,
            "昆柳龙直流输电系统",
            multi,
            8000,
            1489,
            southern,
            voltage_kv=800,
            units=[unit("极Ⅰ"), unit("极Ⅱ")],
            commissioning_events=[
                event("2020-07-31", "昆龙两端低端"),
                event("2020-12-27", "三端"),
            ],
        ),
        system(
            49,
            "张北柔性直流输电系统",
            multi,
            4500,
            766,
            state,
            units=[
                unit("正极", "2022-01-04", 500),
                unit("负极", "2022-01-04", 500),
            ],
        ),
        system(
            50,
            "舟山柔性直流输电系统",
            multi,
            1000,
            281,
            state,
            units=[
                unit("正极", "2014-07-04", 200),
                unit("负极", "2014-07-04", 200),
            ],
        ),
        system(
            51,
            "南澳柔性直流输电系统",
            multi,
            150,
            62,
            southern,
            voltage_kv=160,
            units=[unit("单极", "2013-12-25", source_note_zh="三端")],
        ),
    ]

    table_4_5_ref = {
        "source_id": SOURCE["id"],
        "table": "4-5",
        "physical_pdf_pages": [124, 125],
        "printed_report_pages": [118, 119],
        "mapping_note": "station names paired in the system order used by Table 4-1",
    }
    table_4_8_ref = {
        "source_id": SOURCE["id"],
        "table": "4-8",
        "physical_pdf_pages": [128, 129],
        "printed_report_pages": [122, 123],
        "mapping_note": "station names paired in the system order used by Table 4-1",
    }
    nrec_ref = {
        "source_id": NREC_SOURCE["id"],
        "published_on": NREC_SOURCE["published_on"],
        "url": NREC_SOURCE["url"],
    }

    for value in systems:
        sequence = value["nea_sequence"]
        value["source_ref"] = table_source_ref(sequence)
        if sequence in TERMINAL_PAIRS:
            pair = TERMINAL_PAIRS[sequence]
            if sequence <= 17:
                terminal_ref = table_4_5_ref
                coverage = "official_station_names_no_coordinates"
            elif sequence == 18:
                terminal_ref = nrec_ref
                coverage = "first_party_station_names_no_coordinates"
            else:
                terminal_ref = table_4_8_ref
                coverage = "official_station_names_no_coordinates"
            value["terminals"] = source_terminal_pair(
                pair[0], pair[1], source_ref=terminal_ref
            )
            value["terminal_coverage"] = coverage
        else:
            value["terminals"] = []
            value["terminal_coverage"] = (
                "not_enumerated_in_selected_sources_no_coordinates_inferred"
            )
    return systems


def summary_for(systems: list[dict[str, Any]]) -> dict[str, Any]:
    groups: dict[str, dict[str, int]] = defaultdict(
        lambda: {
            "system_count": 0,
            "rated_transfer_capacity_mw": 0,
            "line_length_km": 0,
        }
    )
    total = {
        "system_count": 0,
        "rated_transfer_capacity_mw": 0,
        "line_length_km": 0,
    }
    for value in systems:
        group = groups[value["system_type"]]
        group["system_count"] += 1
        group["rated_transfer_capacity_mw"] += value[
            "rated_transfer_capacity_mw"
        ]
        group["line_length_km"] += value["line_length_km"]
        total["system_count"] += 1
        total["rated_transfer_capacity_mw"] += value[
            "rated_transfer_capacity_mw"
        ]
        total["line_length_km"] += value["line_length_km"]
    return {"by_system_type": dict(groups), "total": total}


def walk_keys(value: Any) -> list[str]:
    keys: list[str] = []
    if isinstance(value, dict):
        for key, child in value.items():
            keys.append(key)
            keys.extend(walk_keys(child))
    elif isinstance(value, list):
        for child in value:
            keys.extend(walk_keys(child))
    return keys


def validate(systems: list[dict[str, Any]], summary: dict[str, Any]) -> None:
    sequences = [value["nea_sequence"] for value in systems]
    if sequences != list(range(1, 52)):
        raise ValueError("NEA sequences must be exactly 1 through 51 in order")
    if summary["by_system_type"] != EXPECTED_SUMMARY:
        raise ValueError(
            "System-type summary differs from the NEA Table 4-1 totals: "
            f"{summary['by_system_type']}"
        )
    if summary["total"] != EXPECTED_TOTAL:
        raise ValueError(
            "Dataset total differs from the NEA report total: "
            f"{summary['total']}"
        )

    for value in systems:
        sequence = value["nea_sequence"]
        if value["system_type"] not in SYSTEM_TYPES:
            raise ValueError(f"Unknown system type at NEA sequence {sequence}")
        if not value["system_name_zh"]:
            raise ValueError(f"Missing system name at NEA sequence {sequence}")
        for item in value["units"]:
            date = item.get("commissioned_on")
            if date and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", date):
                raise ValueError(
                    f"Invalid commissioning date at NEA sequence {sequence}: {date}"
                )
        if value["capacity_basis"] == "sum_of_reported_unit_ratings":
            unit_total = sum(
                item["rated_transfer_capacity_mw"] for item in value["units"]
            )
            if unit_total != value["rated_transfer_capacity_mw"]:
                raise ValueError(
                    f"Unit capacities do not sum at NEA sequence {sequence}"
                )

    forbidden_geometry_keys = {
        "coordinates",
        "geometry",
        "latitude",
        "longitude",
        "lat",
        "lon",
    }
    present = forbidden_geometry_keys.intersection(walk_keys(systems))
    if present:
        raise ValueError(
            "No inferred map geometry is allowed in this dataset; found "
            + ", ".join(sorted(present))
        )


def make_dataset() -> dict[str, Any]:
    systems = build_systems()
    summary = summary_for(systems)
    validate(systems, summary)
    return {
        "schema_version": SCHEMA_VERSION,
        "dataset_id": DATASET_ID,
        "title": "China HVDC systems in NEA reliability management, 2024",
        "source": SOURCE,
        "supplemental_sources": [NREC_SOURCE],
        "summary": summary,
        "systems": systems,
    }


def json_bytes(value: Any) -> bytes:
    return (
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=False) + "\n"
    ).encode("utf-8")


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_path(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def make_metadata(dataset_bytes: bytes, dataset: dict[str, Any]) -> dict[str, Any]:
    systems = dataset["systems"]
    terminal_system_count = sum(bool(value["terminals"]) for value in systems)
    terminal_count = sum(len(value["terminals"]) for value in systems)
    return {
        "schema_version": SCHEMA_VERSION,
        "dataset_id": DATASET_ID,
        "build_verified_on": BUILD_VERIFIED_ON,
        "builder": "scripts/grid-atlas/build-china-nea-hvdc.py",
        "output": {
            "path": "data/grid-atlas/china-nea-hvdc-systems.json",
            "sha256": sha256_bytes(dataset_bytes),
        },
        "source": SOURCE,
        "supplemental_sources": [NREC_SOURCE],
        "coverage": {
            **dataset["summary"]["total"],
            "by_system_type": dataset["summary"]["by_system_type"],
            "systems_with_verified_terminal_names": terminal_system_count,
            "verified_terminal_names": terminal_count,
            "systems_without_inferred_geometry": len(systems),
        },
        "transformation": [
            (
                "Table 4-1 rows were manually transcribed with original Chinese "
                "system and unit labels, ISO commissioning dates, rated voltage, "
                "rated transfer capacity, line length and grid group."
            ),
            (
                "Back-to-back system totals for sequences 38-44 are sums of "
                "the unit ratings printed in Table 4-1; sequences 45-46 retain "
                "the table's system-level rating without assigning it to units."
            ),
            (
                "Table 4-5 and Table 4-8 station names were paired in Table 4-1 "
                "system order. Sequence 18 terminal names come from the "
                "first-party NR Electric project publication."
            ),
            (
                "No converter-station coordinates, line paths or schematic "
                "geometry were inferred."
            ),
        ],
        "field_scope_notes": {
            "rated_voltage": (
                "Stored at system level only when the source cell applies to the "
                "whole system; otherwise retained on the individual unit."
            ),
            "rated_transfer_capacity_mw": (
                "A nameplate transfer rating, not observed flow, available "
                "capacity, congestion, thermal headroom or real-time dispatch."
            ),
            "line_length_km": (
                "Reported system line length. Zero is retained for back-to-back "
                "systems and does not mean the converter facility has no footprint."
            ),
            "terminals": (
                "Names only. Terminal order is an index, not a claim about "
                "sending/receiving direction."
            ),
        },
        "validation": {
            "expected_summary": {
                "by_system_type": EXPECTED_SUMMARY,
                "total": EXPECTED_TOTAL,
            },
            "checks": [
                "sequences_are_exactly_1_through_51",
                "type_subtotals_match_report",
                "grand_totals_match_report",
                "summed_back_to_back_unit_ratings_match_system_totals",
                "commissioning_dates_use_iso_format",
                "no_geometry_or_coordinate_fields",
            ],
        },
        "limitations": [
            (
                "This is the NEA's 2024 reliability-management snapshot, "
                "published 2025-03-31; it is not a live or exhaustive 2026 grid "
                "inventory."
            ),
            (
                "Table 4-1 supplies system facts but no reusable station "
                "coordinates or surveyed route geometry. This dataset therefore "
                "cannot draw the 51 systems as map lines by itself."
            ),
            (
                "Verified terminal names cover the 37 point-to-point systems. "
                "The selected sources do not enumerate terminal rosters for the "
                "nine back-to-back and five multi-terminal systems, so those "
                "names are not inferred."
            ),
            (
                "Operational reliability, energy-transfer and utilisation "
                "metrics are intentionally excluded: they belong to other report "
                "tables and contain scope/denominator issues that require a "
                "separate audited dataset."
            ),
            (
                "The source report is not redistributed. This repository stores "
                "a factual transcription, source URLs, page references and the "
                "verified PDF SHA-256 digest."
            ),
        ],
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Dataset destination (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--metadata-output",
        type=Path,
        default=DEFAULT_METADATA_OUTPUT,
        help=f"Metadata destination (default: {DEFAULT_METADATA_OUTPUT})",
    )
    parser.add_argument(
        "--source-pdf",
        type=Path,
        help="Optional local source PDF whose pinned SHA-256 must match.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify that existing outputs exactly match a fresh build.",
    )
    return parser.parse_args()


def check_or_write(path: Path, expected: bytes, check: bool) -> None:
    if check:
        if not path.is_file():
            raise SystemExit(f"Missing output for --check: {path}")
        actual = path.read_bytes()
        if actual != expected:
            raise SystemExit(f"Output is stale or differs from the builder: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(expected)


def main() -> None:
    args = parse_args()
    if args.source_pdf:
        source_pdf = args.source_pdf.expanduser().resolve()
        if not source_pdf.is_file():
            raise SystemExit(f"Source PDF does not exist: {source_pdf}")
        digest = sha256_path(source_pdf)
        if digest != SOURCE["pdf_sha256"]:
            raise SystemExit(
                "Source PDF SHA-256 mismatch: "
                f"expected {SOURCE['pdf_sha256']}, got {digest}"
            )

    dataset = make_dataset()
    dataset_bytes = json_bytes(dataset)
    metadata = make_metadata(dataset_bytes, dataset)
    metadata_bytes = json_bytes(metadata)
    check_or_write(args.output.resolve(), dataset_bytes, args.check)
    check_or_write(args.metadata_output.resolve(), metadata_bytes, args.check)

    verb = "Verified" if args.check else "Wrote"
    print(
        f"{verb} {len(dataset['systems'])} systems, "
        f"{dataset['summary']['total']['rated_transfer_capacity_mw']} MW and "
        f"{dataset['summary']['total']['line_length_km']} km"
    )
    print(f"Dataset SHA-256: {sha256_bytes(dataset_bytes)}")
    print(f"Metadata SHA-256: {sha256_bytes(metadata_bytes)}")


if __name__ == "__main__":
    main()
